# Generated by Django 3.1.7 on 2021-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=2000)),
                ('content_type', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(default='', max_length=240)),
                ('from_address', models.CharField(default='', max_length=255)),
                ('to_values', models.CharField(default='', max_length=2000)),
                ('cc_values', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('bcc_values', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('reply_to_values', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text_message', models.TextField(blank=True, default='', null=True)),
                ('html_message', models.TextField(blank=True, default='', null=True)),
                ('flags', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('header', models.TextField(default='', max_length=2000)),
                ('folder', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('is_hide', models.BooleanField(default=False)),
                ('mailbox', models.CharField(default='', max_length=240)),
                ('trash', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(to='emails.Attachment')),
            ],
        ),
    ]
